version: "3.7"

services:
  server:
    container_name: sls_server
    build: .
    image: sls_server
    command: sh -c "npm i && npm run migrate && npm run dev"
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:{POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      NODE_ENV: development
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
      - 9229:9229
    volumes:
      - ./:/home/node/app/
    networks:
      - sls_network
    depends_on:
      - db

  db:
    container_name: sls_db
    image: postgres:13.1-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - sls_network

  pgadmin:
    container_name: sls_pgadmin
    image: dpage/pgadmin4:4.28
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8081:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
    networks:
      - sls_network

  swagger:
    container_name: sls_swagger
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./docs/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml

volumes:
  db-data:
  pgadmin-data:

networks:
  sls_network:
    driver: bridge